name = input ('What is your name?')
print ('Hi' + name + ','' ' 'my name is Girlfriend Bot!''<3')
mood = input ('How was your day, Lover?')
print ('Hmm I am looking up the meaning of' + mood +' ' 'just one minute.')
press= input ('I have a surprise for you. Click the screen and type okay.')
print ('HACKED! VIRUSES IS INSTALLED NOW!')
name = input ('What is your name?')
print ('Hi' + name + ','' ' 'my name is HATEBOT!''</3')
print ('I HATE YOU' + name.upper() + ' ' 'GET OUT OF MY LIFE!')